name: Alan5577-ux

on: [push]

jobs:bigprojects
  build:home

    runs-on: ubuntu-latest

    steps:
    - uses: Alan5577-ux@gmail.com
    - name: Alan5577-uk
      run: echo Hello, world!
    - name: Alan5577-ux
      run: bigprojects
        echo Add other actions to build,
        echo test, and deploy your project.
